### ISSUE TITLE
Shouldn't RAX be in clobber list?

### ISSUE THREAD

**Issue by milabs** [rafael-santiago/kook#1]
https://github.com/rafael-santiago/kook/blob/f64deb061f77828be2fd08d4e76bd1419746f4c9/src/linux/memory_utils.c#L52

**Comment by rafael-santiago** [comment]
The code is pretty static and obvious, I do not see any necessity of using it there. Less code and syntax sugar to maintain, less coding mistakes. Thanks anyway!

**Comment by milabs** [comment]
I've  just realized that it was an inline function, not the macro. In case of inline function it doesn't make any sense, you're right ;-)
